version: "3.7"

services:
  database:
    image: mysql
    # build: ./database
    command: --lower_case_table_names=1
    container_name: database
   # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - "./database/mysql:/docker-entrypoint-initdb.d"  
    networks:
      - app-net
    
  backend:
    image: backend
    build: ./backend
    ports:
      - "4001:4001"
    networks:
      - app-net
  frontend:
    image: frontend
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - app-net
    depends_on:
            - backend
   
networks:
  app-net:
    driver: bridge
